from .ksvm import Ksvm
from .kdt import Kdt
from .kgb import Kgb
from .klasso import Klasso
from .kridge import Kridge
from .klinreg import Klinreg
from .krf import Krf
from .kelastic import Kelastic
from .kab import Kab
from .kbag import Kbag
from .kneuralnet import Kneural_network
from .knearest_neighbors import Knearest_neighbors
