from .ksvm import RKsvm
from .kdt import RKdt
from .kgb import RKgb
from .klasso import RKlasso
from .kridge import RKridge
from .klinreg import RKlinreg
from .krf import RKrf
from .kelastic import RKelastic
from .kab import RKab
from .kbag import RKbag
from .kneuralnet import RKneural_network
from .knearest_neighbors import RKnearest_neighbors
