FROM centos:7

# Set root password
RUN echo "kspasskp" | passwd --stdin root

RUN groupadd -g 1000 kskp
RUN useradd -rm -d /home/kskp -s /bin/bash -g kskp -u 1000 -p kspasskp kskp
USER kskp
WORKDIR /home/kskp

# import python3 from pyenv
USER root
RUN yum install -y git gcc bzip2 bzip2-devel openssl openssl-devel readline readline-devel sqlite-devel

WORKDIR /usr/local/
RUN git clone git://github.com/yyuu/pyenv.git ./pyenv
RUN mkdir -p ./pyenv/versions ./pyenv/shims

ENV LANG en_US.utf8
ENV PYTHONIOENCODING utf-8

ENV PYENV_ROOT /usr/local/pyenv
ENV PATH "${PYENV_ROOT}/shims:${PYENV_ROOT}/bin:${PATH}"

RUN pyenv install -v 3.6.0
RUN pyenv global 3.6.0

RUN pip install --upgrade pip

# mchkcsvなどnysol_pythonに存在しないmコマンドもあるためNYSOLも必要
COPY ./nysol-2.4-0.x86_64.rpm /home/kskp/nysol-2.4-0.x86_64.rpm
# for Nysol
RUN yum install -y sudo gem
RUN rpm -ih /home/kskp/nysol-2.4-0.x86_64.rpm

RUN yum install -y libxml2 libxml2-devel
RUN yum install -y gcc-c++
RUN yum install -y boost boost-devel

RUN pip install nysol
