# for OMRON

FROM centos:7

RUN groupadd -g 1000 kskp
RUN useradd -rm -d /home/kskp -s /bin/bash -g kskp -u 1000 -p kspasskp kskp
USER kskp
WORKDIR /home/kskp

# import python3 from pyenv
USER root
RUN yum install -y git gcc bzip2 bzip2-devel openssl openssl-devel readline readline-devel
WORKDIR /usr/local/
RUN git clone git://github.com/yyuu/pyenv.git ./pyenv
RUN mkdir -p ./pyenv/versions ./pyenv/shims

ENV LANG en_US.utf8
ENV PYTHONIOENCODING utf-8

RUN yum install -y sqlite-*

ENV PYENV_ROOT /usr/local/pyenv
ENV PATH "${PYENV_ROOT}/shims:${PYENV_ROOT}/bin:${PATH}"

RUN pyenv install -v 3.6.0
RUN pyenv global 3.6.0

RUN pip install --upgrade pip

COPY ./nysol-2.4-0.x86_64.rpm /home/kskp/nysol-2.4-0.x86_64.rpm
# for Nysol
RUN yum install -y sudo gem
RUN rpm -ih /home/kskp/nysol-2.4-0.x86_64.rpm

USER kskp
COPY ./kskp /home/kskp/kskp

COPY ./setup.py /home/kskp/setup.py

USER root
ENV FLASK_APP kskp
RUN pip install -e /home/kskp

COPY ./kskp/config/small.cfg /home/kskp/kskp/settings.cfg



RUN yum install -y libxml2 libxml2-devel
RUN yum install -y gcc-c++
RUN yum install -y boost boost-devel

RUN pip install nysol

# install nkf
RUN yum install -y epel-release
RUN yum install -y nkf --enablerepo=epel

WORKDIR /home/kskp

USER kskp
CMD flask run -h 0.0.0.0 -p ${PORT:-5000}
