name: KSKP-test

on:
  push:
    branches:
      - develop_github_actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python3.6.4
        uses: actions setup-python@v1
        with:
          python-version: 3.6.4
      - name: Set up kskp(Continuous Integration)
        run: |
          sh $HOME/kskp-web/.github/workflows/kskpinstall.sh
      - name: test kskp(Continuous Integration)
        run: |
          docker exec kskp "python3 -m unittest kskp.web.backend.api.tests.test_lib.LibraryTestCase"
