name: KSKP-test

on:
  push:
    branches:
      - develop_github_actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: deploy kskp to AWS(Continuous delivery)
        run: |
          sudo apt-get install sshpass
          sshpass -p ${{secrets.AWS_PASSWORD}} ssh -o StrictHostKeyChecking=no ${{secrets.SERVER_USER}}@${{secrets.SERVER_IP}} "
            if [ -e kskp-web -a -e kskp-flow-engine -a -e kskp-data-store ]; then
              cd kskp-web
              git pull
              cd ../kskp-flow-engine
              git pull
              cd ../kskp-data-store
              git pull
            else
              git clone https://df86786e5c82ad6f92312b83afb0107529f7ea68:x-oauth-basic@github.com/ksk-anl/kskp-flow-engine.git
              git clone https://df86786e5c82ad6f92312b83afb0107529f7ea68:x-oauth-basic@github.com/ksk-anl/kskp-data-store.git
              git clone https://df86786e5c82ad6f92312b83afb0107529f7ea68:x-oauth-basic@github.com/ksk-anl/kskp-web.git
            fi
            "
