name: KSKP-test

on:
  push:
    branches:
      - develop_github_actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Set up kskp(Continuous Integration)
        run: |
          POSTGRES_CID=$(docker ps -a -f name=postgres-kskp)
          KSKP_CID=$(docker ps -a -f name=kskp)
          if [ "${POSTGRES_CID" -a "${KSKP_CID" ]; then
            cd kskp-web
            npm start
            docker run postgres-kskp
            docker run -i -d kskp
          else
            sudo apt-get -y install git docker
            git clone git://github.com/nodenv/nodenv.git ~/.nodenv
            git clone git://github.com/nodenv/node-build.git ~/.nodenv/plugins/node-build
            echo 'export PATH="$HOME/.nodenv/bin:$PATH"' >> ~/.bash_profile
            echo 'eval "$(nodenv init -)"' >> ~/.bash_profile
            source ~/.bash_profile
            nodenv install 8.12.0
            nodenv global 8.12.0
            cd ../
            mkdir kskp-test
            cd kskp-test
            git clone https://df86786e5c82ad6f92312b83afb0107529f7ea68:x-oauth-basic@github.com/ksk-anl/kskp-flow-engine.git
            git clone https://df86786e5c82ad6f92312b83afb0107529f7ea68:x-oauth-basic@github.com/ksk-anl/kskp-data-store.git
            git clone https://df86786e5c82ad6f92312b83afb0107529f7ea68:x-oauth-basic@github.com/ksk-anl/kskp-web.git
            cd kskp-web/kskp
            npm install
            npm run dll
            npm run build
            cd ..
            docker build -f docker/Dockerfile -t kskp .
            docker run --name postgres-kskp -e POSTGRES_DB=kskp -p 5432:5432 -d postgres
            cd ..
            docker run --privileged -e FLASK_ENV=development -e FLASK_DEBUG=1 -e "TZ=Asia/Tokyo" -d -p 5000:5000 -v "$(pwd)"/:/home/kskp/ --link postgres-kskp:db --name kskp kskp
          fi
      - name: test kskp(Continuous Integration)
        run: |
          docker exec kskp "python3 -m unittest kskp.web.backend.api.tests.test_lib.LibraryTestCase"
