name: KSKP-Test

on:
  push:
    branches:
      - develop_github_actions
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Set up kskp(Continuous Integration)
        run: |
          sudo apt-get -y install git docker
          git clone https://df86786e5c82ad6f92312b83afb0107529f7ea68:x-oauth-basic@github.com/ksk-anl/kskp-cli.git
          sudo sh ./kskp-cli/install.sh
          kskp install develop
          docker start kskp
          docker exec -it develop_kskp-ap_1 /bin/bash
          python -m unittest kskp.backend.api.tests.test_auth
          python -m unittest kskp.web.backend.api.tests.test_lib.DataStoreTestCase
          python -m unittest kskp.web.backend.api.tests.test_lib.LibraryTestCase
