name: KSKP-Test_schedule_action

on:
  schedule:
    - cron: "30 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up kskp(Continuous Integration)
        shell: bash
        run: |
          sudo apt-get -y install git docker build-essential checkinstall
          git clone -b github_actions https://df86786e5c82ad6f92312b83afb0107529f7ea68:x-oauth-basic@github.com/ksk-anl/kskp-cli.git
          cd kskp-cli
          sudo ln -sf $(pwd)/kskp /usr/local/bin/kskp
          source <(echo 'export KSKP_CLI='`pwd`)
          kskp install schedule_action
          docker start schedule_action_kskp-ap_1

      - name: test KSKP-Web
        shell: bash
        run: |
          docker exec schedule_action_kskp-ap_1 /bin/bash -c ' \
          python -m unittest kskp.web.backend.api.tests.test_auth && \
          python -m unittest kskp.web.backend.api.tests.test_lib.DataStoreTestCase && \
          python -m unittest kskp.web.backend.api.tests.test_lib.LibraryTestCase
          '
