name: KSKP_remote_unit_test

on  :
    push:

jobs:
    throw test repo:
        runs-on:    ubuntu-latest
        steps:
            -   name: throw http reqest for test repo
                run: |
                    curl -X POST https://api.github.com/repos/ksk-anl/kskp-test/dispatches \
                    -H 'Accept: application/vnd.github.everest-preview+json' \
                    -u ${{ secrets.ACCESS_TOKEN }} \
                    --data '{"event_type": "send_message", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'